@hostname = localhost
@port = 3000
@api = auth
@test_id = 1
@encoded = c3R5bGVAZ21haWwuY29tOjFxMnczZTRyISE=

### 신규 계정 등록
POST http://{{hostname}}:{{port}}/{{api}}/register
Authorization: Basic {{encoded}}

### 로그인
POST http://{{hostname}}:{{port}}/{{api}}/login
Authorization: Basic {{encoded}}