@hostname = localhost
@port = 3000
@api = movie
@test_id = 4

### Get (전체조회)
GET http://{{hostname}}:{{port}}/{{api}}

### Get (이름으로 조회)
GET http://{{hostname}}:{{port}}/{{api}}?name=해리

### Create
POST http://{{hostname}}:{{port}}/{{api}}
Content-Type: application/json

{
  "name": "셜록홈즈",
  "genre": "action",
  "character": ["셜록 홈즈", "존 왓슨"]
}

### Update
PUT http://{{hostname}}:{{port}}/{{api}}/{{test_id}}
Content-Type: application/json

{
  "name": "나니아",
  "genre": "fantasy",
  "character": [""]
}


### Delete
DELETE http://{{hostname}}:{{port}}/{{api}}/{{test_id}}
