@hostname = localhost
@port = 3000
@api = movie
@test_id = 7

### Get (전체조회)
GET http://{{hostname}}:{{port}}/{{api}}

### Get (이름으로 조회)
GET http://{{hostname}}:{{port}}/{{api}}?name=해리

### Get (id로 조회)
GET http://{{hostname}}:{{port}}/{{api}}/{{test_id}}

### Create
POST http://{{hostname}}:{{port}}/{{api}}
Content-Type: application/json

{
  "name": "몬스터헌터와일즈",
  "genre": "fantasy",
  "character": ["리오레우스"],
  "detail": "몬스터헌터 시리즈 최신작"
}

### Update
PUT http://{{hostname}}:{{port}}/{{api}}/{{test_id}}
Content-Type: application/json

{
  "name": "몬스터헌터 와일즈",
  "detail": "몬스터헌터 시리즈 최신작입니다."
}


### Delete
DELETE http://{{hostname}}:{{port}}/{{api}}/{{test_id}}
