@hostname = localhost
@port = 3000
@api = movie
@test_id = 6

### Get (전체조회)
GET http://{{hostname}}:{{port}}/{{api}}

### Get (이름으로 조회)
GET http://{{hostname}}:{{port}}/{{api}}?name=해리

### Get (id로 조회)
GET http://{{hostname}}:{{port}}/{{api}}/{{test_id}}

### Create
POST http://{{hostname}}:{{port}}/{{api}}
Content-Type: application/json

{
  "name": "신비한 동물 사전3",
  "genres": ["액션", "판타지", "마법", "서사"],
  "character": ["마법사", "그린델왈드"],
  "detail": "해리포터 프리퀄",
  "directorId": 1
}

### Update
PUT http://{{hostname}}:{{port}}/{{api}}/{{test_id}}
Content-Type: application/json

{
  "name": "신비한 동물 사전 3",
  "detail": "해리포터 세계관의 프리퀄.",
  "character": ["뉴트 스캐맨더", "티나 골드스틴", "퀴니 골드스틴", "제이콥 코왈스키", "그린델왈드"],
  "genres": ["액션", "판타지"],
  "directorId": 1
}


### Delete
DELETE http://{{hostname}}:{{port}}/{{api}}/{{test_id}}
